// // import type { Metadata } from "next";
// // import { Geist, Geist_Mono } from "next/font/google";
// // import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }

// import "./globals.css";
// import { Inter } from "next/font/google";

// // Initialize the Inter font with specific subsets
// const inter = Inter({ subsets: ["latin"] });

// // Metadata for the application (SEO purposes)
// export const metadata = {
//   title: "MUSBAHDEV - Your Digital Services Solution",
//   description:
//     "MUSBAHDEV connects you with reliable professionals for all your home repair, maintenance, and improvement needs.",
// };

// // Root layout component
// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en" className={inter.className}>
//       <head>
//         {/* No Font Awesome needed, as we'll use Lucide React icons */}
//       </head>
//       <body className="antialiased bg-[var(--color-light-bg)] text-[var(--color-dark-text)]">
//         {children}
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import { Inter } from "next/font/google";
import { AuthProvider } from "../context/AuthContext"; // Import AuthProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "MUSBAHDEV - Your Digital Services Solution",
  description:
    "MUSBAHDEV connects you with reliable professionals for all your home repair, maintenance, and improvement needs.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        {/* No Font Awesome needed, as we'll use Lucide React icons */}
      </head>
      <body className="antialiased bg-[var(--color-light-bg)] text-[var(--color-dark-text)]">
        <AuthProvider>
          {" "}
          {/* Wrap children with AuthProvider */}
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
